name: AgentFormer
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=1.8.0
  - torchvision=0.9.0
  - torchaudio=0.8.0
  - cudatoolkit=11.1
  - pip
  - pip:
    - -r requirements.txt